// <auto-generated />
using System;
using FitnessCenter.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCenter.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206140839_UserAppointmentOneToManyRelationship")]
    partial class UserAppointmentOneToManyRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessCenter.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("FitnessCenter.Models.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("FitnessCenter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClosingTime = new TimeSpan(0, 23, 59, 0, 0),
                            Description = "Türkiye'nin en modern fitness merkezi ile hayalinizdeki vücuda kavuşun. \r\n                Profesyonel eğitmenler, son teknoloji ekipmanlar ve kişiselleştirilmiş programlarla \r\n                fitness yolculuğunuza başlayın.",
                            Name = "IronCore",
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("FitnessCenter.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tüm kardiyo ve ağırlık ekipmanlarına sınırsız erişim. Salon kullanım bileti.",
                            DurationMinutes = 60,
                            Fee = 10.0,
                            IsActive = true,
                            MaxCapacity = 50,
                            Name = "Açık Alan Serbest Fitness"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Temel kaldırma ve direnç tekniklerine odaklanan, ağırlık merkezli grup dersi.",
                            DurationMinutes = 60,
                            Fee = 25.0,
                            IsActive = true,
                            MaxCapacity = 10,
                            Name = "STRENGTH - Kas Güçlendirme"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kickboks teknikleri ile yoğun kardiyo ve güç eğitimi. Ekipman temin edilir.",
                            DurationMinutes = 60,
                            Fee = 22.0,
                            IsActive = true,
                            MaxCapacity = 10,
                            Name = "BOXING"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dinamik akış ve nefes kontrolüne odaklanan denge seansı.",
                            DurationMinutes = 60,
                            Fee = 20.0,
                            IsActive = true,
                            MaxCapacity = 10,
                            Name = "Vinyasa Flow Yoga"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Merkez kuvveti ve esnekliği geliştirmeye odaklanan temel seviye mat dersi.",
                            DurationMinutes = 60,
                            Fee = 18.0,
                            IsActive = true,
                            MaxCapacity = 10,
                            Name = "Mat Pilates"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bale, yoga ve pilates hareketlerinin birleşimiyle kasları uzatma ve tonlama dersi.",
                            DurationMinutes = 60,
                            Fee = 28.0,
                            IsActive = true,
                            MaxCapacity = 10,
                            Name = "BARRE Dersi"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Günlük olarak Hamam, Sauna ve dinlenme odası erişim bileti.",
                            DurationMinutes = 60,
                            Fee = 35.0,
                            IsActive = true,
                            MaxCapacity = 10,
                            Name = "Spa & Hamam Erişimi"
                        });
                });

            modelBuilder.Entity("FitnessCenter.Models.ServiceTrainer", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "TrainerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("ServiceTrainers");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            TrainerId = 6
                        },
                        new
                        {
                            ServiceId = 2,
                            TrainerId = 2
                        },
                        new
                        {
                            ServiceId = 3,
                            TrainerId = 4
                        },
                        new
                        {
                            ServiceId = 4,
                            TrainerId = 3
                        },
                        new
                        {
                            ServiceId = 5,
                            TrainerId = 5
                        },
                        new
                        {
                            ServiceId = 6,
                            TrainerId = 5
                        },
                        new
                        {
                            ServiceId = 7,
                            TrainerId = 6
                        },
                        new
                        {
                            ServiceId = 2,
                            TrainerId = 6
                        },
                        new
                        {
                            ServiceId = 3,
                            TrainerId = 1
                        });
                });

            modelBuilder.Entity("FitnessCenter.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Uzmanlık alanı fonksiyonel antrenmanlar ve kardiyo. 10 yıllık deneyim.",
                            Name = "Kadir Nasir",
                            ProfileImageUrl = "/images/trainers/kadirNasir.jpg",
                            Specialty = "HIIT & Cardio"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Vücut geliştirme, güçlenme ve beslenme programları. IFBB sertifikalı.",
                            Name = "Deniz Yılmaz",
                            ProfileImageUrl = "/images/trainers/denizYilmaz.jpg",
                            Specialty = "Kas Geliştirme & Güçlenme"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Esneklik, denge ve stres azaltma üzerine yoğunlaşmıştır. Uluslararası Yoga Eğitmeni.",
                            Name = "Ece Kaya",
                            ProfileImageUrl = "/images/trainers/eceKaya.jpg",
                            Specialty = "Yoga & Barre"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Maraton ve triatlon hazırlıklarında uzmanlaşmıştır. Hızlı ve kalıcı sonuçlar.",
                            Name = "Furkan Demir",
                            ProfileImageUrl = "/images/trainers/furkanDemir.jpg",
                            Specialty = "Boxing & Fonksiyonel Antrenman"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Postür düzeltme ve sırt ağrısı tedavisine yönelik mat ve reformer pilates uzmanı.",
                            Name = "Gizem Akın",
                            ProfileImageUrl = "/images/trainers/gizemAkin.jpg",
                            Specialty = "Pilates & Core Stability"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Günlük hareket kalitesini artıran, yüksek yoğunluklu fonksiyonel dersler vermektedir.",
                            Name = "Hakan Can",
                            ProfileImageUrl = "/images/trainers/hakanCan.jpg",
                            Specialty = "Genel Fitness & Wellness"
                        });
                });

            modelBuilder.Entity("FitnessCenter.Models.TrainerAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            StartTime = new TimeSpan(0, 15, 0, 0, 0),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            StartTime = new TimeSpan(0, 15, 0, 0, 0),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            StartTime = new TimeSpan(0, 15, 0, 0, 0),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 19,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 20,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            TrainerId = 6
                        },
                        new
                        {
                            Id = 21,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            TrainerId = 6
                        },
                        new
                        {
                            Id = 22,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            TrainerId = 6
                        },
                        new
                        {
                            Id = 23,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            StartTime = new TimeSpan(0, 16, 0, 0, 0),
                            TrainerId = 6
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FitnessCenter.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("FitnessCenter.Models.Appointment", b =>
                {
                    b.HasOne("FitnessCenter.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessCenter.Models.ServiceTrainer", b =>
                {
                    b.HasOne("FitnessCenter.Models.Service", "Service")
                        .WithMany("ServiceTrainers")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenter.Models.Trainer", "Trainer")
                        .WithMany("ServiceTrainers")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessCenter.Models.TrainerAvailability", b =>
                {
                    b.HasOne("FitnessCenter.Models.Trainer", "Trainer")
                        .WithMany("Availabilities")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCenter.Models.Service", b =>
                {
                    b.Navigation("ServiceTrainers");
                });

            modelBuilder.Entity("FitnessCenter.Models.Trainer", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("ServiceTrainers");
                });

            modelBuilder.Entity("FitnessCenter.Models.User", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
